add oauth2-backend-cats
ocadotechnology/sttp-oauth2 pull request #46
Opened 2021-03-09 10:10 UTC by bwiercinski

* add `Cache` abstraction
 * add `SttpOauth2ClientCredentialsCatsBackend`, which can:
   * fetch token using `ClientCredentialsProvider`
   * reuse token multiple times using cache
   * fetch new token if the previous expires
   * add `Authorization` header

2021-03-09 10:17 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +      .filter { case (TokenWithExpiryInstant(_, expiryInstant), currentInstant) => currentInstant isBefore expiryInstant }
possible bug:
if this check (`isBefore`) is evaluated just before token expires, then because of duration of request dispatching and network latency, when the request will come to an auth server it may be already expired.

i see 2 options: 
 * **retry whole process once when 401 will be responded**
 * add threshold (let say default 10 seconds). then use (expiryInstant - threshold)

2021-03-09 23:12 UTC, kubukoz commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +      .filter { case (TokenWithExpiryInstant(_, expiryInstant), currentInstant) => currentInstant isBefore expiryInstant }
I think this will be so rare that we don't need to care for now, retries can be added to the underlying backend / in another backend wrapping this. Probably not worth the complexity of having a threshold or building retries into this backend.

2021-03-09 23:33 UTC, kubukoz requested changes

2021-03-09 23:59 UTC, kubukoz commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  clientCredentialsProvider: ClientCredentialsProvider[F],
Just noticed something cool, instead of passing CCP + scope, we can pass an `F[Token]` and actually combine the two parameters in the "constructor".

2021-03-10 06:44 UTC, majk-p commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +      .filter { case (TokenWithExpiryInstant(_, expiryInstant), currentInstant) => currentInstant isBefore expiryInstant }
Agreed with @kubukoz. We can leave an issue and revisit that in future.

2021-03-10 08:22 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  ): F[SttpOauth2ClientCredentialsCatsBackend[F, P]] = {
someone can use this type to ensure that some client has ClientCredentialsBackend as an input. of course if someone wants to stick with `SttpBackend` he is more than welcome to do so. it is not my business

2021-03-10 08:24 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  def apply[F[_]: Concurrent: Clock, P](
`.apply` i'm following sttp conventions.

https://github.com/softwaremill/sttp/blob/master/akka-http-backend/src/main/scala/sttp/client3/akkahttp/AkkaHttpBackend.scala#L191
https://github.com/softwaremill/sttp/blob/master/async-http-client-backend/cats/src/main/scala/sttp/client3/asynchttpclient/cats/AsyncHttpClientCatsBackend.scala#L80

and so on

2021-03-10 08:27 UTC, bwiercinski commented on build.sbt
> +    libraryDependencies ++= oauth2Dependencies ++ Seq(
well i very dislike how dependencies are grouped in build.sbt.

there are stupid `val cats = Seq("cats-core")` etc. at the end the variable is used only once because it is defined inside block. i will try to come to something compromising

2021-03-10 08:29 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  val scope: Scope
i wanted to make some kind of utility, of this but okay i'm not forcing that

2021-03-10 08:30 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  private def requestAndSaveToken: F[TokenWithExpiryInstant] =
it is based on `ClientCredentialsProvider::requestToken`

2021-03-10 08:32 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  private def requestAndSaveToken: F[TokenWithExpiryInstant] =
changed but i can undo

2021-03-10 08:41 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +      .filter { case (TokenWithExpiryInstant(_, expiryInstant), currentInstant) => currentInstant isBefore expiryInstant }
https://github.com/ocadotechnology/sttp-oauth2/issues/48

2021-03-10 08:42 UTC, bwiercinski commented on build.sbt
> +    libraryDependencies ++= oauth2Dependencies ++ Seq(
also why this is called "commonDependencies" :p

2021-03-10 08:56 UTC, bwiercinski commented on oauth2-backend-cats/src/test/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackendSpec.scala
> +        request.forceBodyAsString == "grant_type=client_credentials&" +
it will add more complexity than benefits. now these tests read well

2021-03-10 09:14 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +      .filter { case (TokenWithExpiryInstant(_, expiryInstant), currentInstant) => currentInstant isBefore expiryInstant }
https://github.com/ocadotechnology/sttp-oauth2/pull/46/commits/5c5a8b06279cb38c62cf365cfe8a862f6f138f18

2021-03-10 09:14 UTC, bwiercinski commented on build.sbt
> +    libraryDependencies ++= oauth2Dependencies ++ Seq(
https://github.com/ocadotechnology/sttp-oauth2/pull/46/commits/5c5a8b06279cb38c62cf365cfe8a862f6f138f18

2021-03-10 11:31 UTC, kubukoz commented on build.sbt
> +    libraryDependencies ++= oauth2Dependencies ++ Seq(
lgtm

2021-03-10 11:35 UTC, kubukoz commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  ): F[SttpOauth2ClientCredentialsCatsBackend[F, P]] = {
mmmmm fine 👍

2021-03-10 11:36 UTC, kubukoz commented on oauth2-backend-cats/src/test/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackendSpec.scala
> +        request.forceBodyAsString == "grant_type=client_credentials&" +
okay then

2021-03-10 11:36 UTC, kubukoz approved these changes

2021-03-10 12:07 UTC, bwiercinski commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackend.scala
> +  private def requestAndSaveToken: F[TokenWithExpiryInstant] =
lets leave fetch

2021-03-10 12:11 UTC, bwiercinski commented on oauth2-backend-cats/src/test/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsCatsBackendSpec.scala
> +          _         <- IO.sleep(200.millis)
i will try to educate myself and solve it in separate MR.

2021-03-11 15:09 UTC, majk-p approved these changes

2021-03-11 17:01 UTC, merged