add oauth2-backend-future module and SttpOauth2ClientCredentialsFutureBackend
ocadotechnology/sttp-oauth2 pull request #54
Opened 2021-03-18 10:59 UTC by bwiercinski

same functionalities like in cats backend, but using Future and Java SDK's Semaphore and AtomicReference

2021-03-18 13:33 UTC, kubukoz requested changes

2021-03-18 13:53 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    _        <- Future(semaphore.acquire())
nice i was looking for such thing, but found only for twitter Future. not i've implemented Cache using monix's AtomicAny as well

2021-03-18 13:53 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    _        <- Future(semaphore.release())
you are right, but now it is outdated

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-cats/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/CatsRefCache.scala
> +class CatsRefCache[F[_], A] private (ref: Ref[F, Option[A]]) extends Cache[F, A] {
final :trollface:

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +class MonixFutureCache[A](implicit ec: ExecutionContext) extends Cache[Future, A] {
final

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +  val ref: AtomicAny[Option[A]] = AtomicAny(Option.empty[A])
private

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +  override def get: Future[Option[A]] = Future(ref.get())
tbh it might be better to actually do `Future.successful`, no need to force a task submission to the EC. Same in `set`

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    fetchTokenAction().map(calculateExpiryInstant).flatTap(cache.set)
Not sure how it works by default in backends, but this must have some sort of timeout or you'll block your entire app from making any requests... wonder if we should add a timeout somewhere in this backend just to be safe

2021-03-18 14:37 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/TimeProvider.scala
> +  val default: TimeProvider = new TimeProvider {
I believe this is a SAM: `val default: TimeProvider = () => Instant.now()`

2021-03-18 14:45 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/TimeProvider.scala
> +  val default: TimeProvider = new TimeProvider {
well I dislike using it when it is not so obvious what is the name of implemented method

2021-03-18 14:48 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/TimeProvider.scala
> +  val default: TimeProvider = new TimeProvider {
it's right above it :P but I won't insist

2021-03-18 14:50 UTC, kubukoz approved these changes
Just some nitpicks I have but nothing serious anymore, good stuff

2021-03-18 14:52 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    fetchTokenAction().map(calculateExpiryInstant).flatTap(cache.set)
it depends how client will configure provisioned backend. all known for me backends have default timeout set to 30 seconds (https://github.com/softwaremill/sttp/blob/8d41139c727985f743a167982dcbc82816bc5265/core/src/main/scala/sttp/client3/SttpBackendOptions.scala#L99-L102). so if the user override this option then he knows what he is doing.

that's great in this project that it is used provisioned backend and not some guerrilla backends with inaccessible configuration

2021-03-18 14:53 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +  override def get: Future[Option[A]] = Future(ref.get())
hmm shouldn't we treat this as a side-effect?

2021-03-18 15:57 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +  override def get: Future[Option[A]] = Future(ref.get())
Future isn't meant for suspending side effects and isn't even able to. The only valid reason I see to use `Future.apply(...)` is to make sure your computation runs on the `ExecutionContext` in scope (and if that computation can throw, this will also ensure the exception is caught in the Future, unless fatal) :)

2021-03-18 15:59 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/MonixFutureCache.scala
> +  override def get: Future[Option[A]] = Future(ref.get())
ok i will use Future.successful

2021-03-18 16:00 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    fetchTokenAction().map(calculateExpiryInstant).flatTap(cache.set)
okay ;)

> guerrilla backends

😂

2021-03-18 16:06 UTC, bwiercinski commented on build.sbt
> +      "io.monix" %% "monix-execution" % Versions.monix,
i'm using only necessary subproject of whole `monix`

pls talk with @kubukoz , because You both advising me opposite suggestions :/ 

i could try to use `blocking {}` and SDK Semaphore, but pls be patient because i have no clue how to use this :p

2021-03-18 17:06 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    tokenWithExpiryInstant <- cachedToken.filter(currentInstant isBefore _.expiryInstant).fold(fetchAndSaveToken())(Future.successful)
why does it have disadvantages?

2021-03-18 17:26 UTC, kubukoz commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    tokenWithExpiryInstant <- cachedToken.filter(currentInstant isBefore _.expiryInstant).fold(fetchAndSaveToken())(Future.successful)
Confusing predecence rules, doesn't work with multi-parameter functions, brings trouble for formatting (you can't just do a newline before `isBefore` here)... in general I think the sane default is to disallow it for non-symbolic operators (with exceptions, like scalatest).

We could add a scalafmt rule: https://scalameta.org/scalafmt/docs/configuration.html#avoidinfix

and possibly override the config for tests to allow infixes in scalatest suites.

2021-03-18 18:15 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    tokenWithExpiryInstant <- cachedToken.filter(currentInstant isBefore _.expiryInstant).fold(fetchAndSaveToken())(Future.successful)
i thought, i wasn't overusing infix. i like to use infix in operator-like methods for example

`x.and(y)` -> `x and y` (of course when `x` and `y` expressions are relatively small)
`x.compareTo(y)` -> `x compareTo y`

`isBefore` is basically `<` operator for instant. it is like `currentInstant < _.expiryInstant`. i can add `Order[Instant]` and use `<`, but I dont see a reason to not use `isBefore`.

2021-03-19 00:09 UTC, tplaskowski commented on build.sbt
> +      "io.monix" %% "monix-execution" % Versions.monix,
@kubukoz ok, but still you are adding it to the dependency, with the version etc. etc. I would be surprised as a user that something that tends to be _pure future_ brings me monix into dependency tree.

I don't have anything against using monix, because it's great, but that should be exposed to the user. If not in the name, then in the doc 😉

2021-03-19 00:22 UTC, tplaskowski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    tokenWithExpiryInstant <- cachedToken.filter(currentInstant isBefore _.expiryInstant).fold(fetchAndSaveToken())(Future.successful)
I think it's just confusing for non-symbolic methods, if I just scan the code then in this part I need to think twice about what is going on here. And you've just saved space for one character.

And I like that scalafmt rule, plus it will be [deprecated](https://dotty.epfl.ch/docs/reference/changed-features/operators.html#motivation-1) in Scala 3 (from 3.1).

2021-03-19 00:27 UTC, kubukoz commented on build.sbt
> +      "io.monix" %% "monix-execution" % Versions.monix,
I'm pretty sure you mostly like the parts of monix that aren't even in that module :D Task isn't there, for example.

It is exposed to the user if they check their dependency tree. But a mention in the readme would be worth having anyway.

2021-03-19 00:42 UTC, tplaskowski approved these changes
Good stuff. So I'm happy to see it merged.

2021-03-19 08:34 UTC, bwiercinski commented on oauth2-backend-future/src/main/scala/com/ocadotechnology/sttp/oauth2/backend/SttpOauth2ClientCredentialsFutureBackend.scala
> +    tokenWithExpiryInstant <- cachedToken.filter(currentInstant isBefore _.expiryInstant).fold(fetchAndSaveToken())(Future.successful)
it was my point of view, of course i can replace this to standard notation

2021-03-19 09:20 UTC, bwiercinski commented on build.sbt
> +      "io.monix" %% "monix-execution" % Versions.monix,
added note

2021-03-19 09:21 UTC, merged