Support custom login/token URLs
ocadotechnology/sttp-oauth2 pull request #71
Opened 2021-05-07 10:44 UTC by majk-p

Resolves https://github.com/ocadotechnology/sttp-oauth2/issues/9

2021-05-10 11:42 UTC, tplaskowski requested changes

2021-05-10 11:42 UTC, tplaskowski commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +    tokenPath: List[String]
I think it should be something like `tokenPathSegments` etc.

2021-05-10 13:41 UTC, kubukoz commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +  final case class PathsConfig(
I wouldn't stick to `Paths` in the name, just `ProviderConfig` or `AuthorizationCodeProvider.Config` would be precise enough, and flexible enough to allow adding more things in the future.

2021-05-10 13:43 UTC, kubukoz commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +    tokenPath: List[String]
that, or we could have a `Path` newtype / ADT instead of lists of strings

2021-05-10 13:44 UTC, kubukoz commented on oauth2/src/test/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProviderSpec.scala
> +            .withPath(configuration.loginPath)
This feels like duplication of the logic in the code under test :)

2021-05-10 16:22 UTC, kubukoz commented on oauth2/src/test/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProviderSpec.scala
> +            .withPath(configuration.loginPath)
The problem here is that if you made the same mistake in the test and implementation, you wouldn't catch it. With concrete strings it'd be more bulletproof, and I'd go as far as to compare the string representation instead of sttp's model (or construct the model in a more direct way, like `new Uri(path = ..., params = ...)` if possible)

2021-05-11 08:50 UTC, majk-p commented on oauth2/src/test/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProviderSpec.scala
> +            .withPath(configuration.loginPath)
Introduced `UriUtils`:
```scala
object UriUtils {
  private def tupleToParam(k: String, v: String) = s"$k=$v"

  def expectedResult(baseUri: Uri, path: AuthorizationCodeProvider.Config.Path, params: List[(String, String)]): String = {
    val paramsSubstring = params.map((tupleToParam _).tupled).mkString("&")
    s"${baseUri.withWholePath(s"${path.values.mkString("/")}").toString()}?$paramsSubstring"
  }
}
```
It's now used instead of this code duplication.

2021-05-11 08:51 UTC, majk-p commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +    tokenPath: List[String]
@tplaskowski I've introduced new config structure 
```scala
final case class Config(
  loginPath: Config.Path,
  logoutPath: Config.Path,
  tokenPath: Config.Path
)

object Config {

  case class Path(segments: List[Segment]) {
    def values: List[String] = segments.map(_.value)
  }

  case class Segment(value: String) extends AnyVal
  /*...*/
}
```

2021-05-13 11:43 UTC, bwiercinski commented on oauth2/src/test/scala/com/ocadotechnology/sttp/oauth2/UriUtils.scala
> +object UriUtils {
private within package?

2021-05-13 14:47 UTC, kubukoz commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +    tokenPath: List[String]
lgtm

2021-05-13 14:48 UTC, kubukoz approved these changes

2021-05-14 05:32 UTC, tplaskowski commented on oauth2/src/main/scala/com/ocadotechnology/sttp/oauth2/AuthorizationCodeProvider.scala
> +    tokenPath: List[String]
Better 🙂

2021-05-14 05:33 UTC, tplaskowski approved these changes

2021-05-14 05:35 UTC, merged