Draft: Docs page
ocadotechnology/sttp-oauth2 pull request #83
Opened 2021-05-15 20:54 UTC by majk-p

2021-05-15 21:50 UTC, majk-p commented
Published to https://ocadotechnology.github.io/sttp-oauth2/

2021-05-15 21:57 UTC, majk-p commented
@kubukoz @tplaskowski please have a look

2021-05-17 12:20 UTC, kubukoz requested changes

2021-05-17 12:20 UTC, kubukoz commented on docs/authorization-code.md
> +description: Authroization code grant documentation
```suggestion
description: Authorization code grant documentation
```

2021-05-17 12:20 UTC, kubukoz commented on docs/client-credentials.md
> +  - reuse the token multiple times using cache (default cache implementation may be overridden using appropriate constructor functions)
```suggestion
  - reuse the token multiple times using a cache (default cache implementation may be overridden using appropriate constructor functions)
```

2021-05-17 12:20 UTC, kubukoz commented on docs/getting-started.md
> +Each grant is implemented in an object with explicit return and error types on methods and additionally, TaglessFinal friendly `*Provider` interface.
```suggestion
Each grant is implemented in an object with explicit return and error types on methods and additionally, Tagless Final friendly `*Provider` interface.
```

2021-05-17 12:20 UTC, kubukoz commented on website/src/components/HomepageFeatures.js
> +        <code>sttp-oauth2</code> supports following following grant types: Authorization code, Password grant, Client credentials
```suggestion
        <code>sttp-oauth2</code> supports the following following grant types: Authorization code, Password grant, Client credentials
```

2021-05-17 14:07 UTC, kubukoz approved these changes
lgtm

2021-05-17 14:10 UTC, merged

2021-05-17 14:10 UTC, kubukoz commented
Move fast, break things :trollface:

2021-05-17 14:11 UTC, kubukoz commented on .github/workflows/mdoc.yml
> +    if: github.event_name != 'pull_request'
General wondering, will this run on pushes to non-main branches? Maybe it'd be better to run this only on main?

2021-05-17 14:15 UTC, majk-p commented on .github/workflows/mdoc.yml
> +    if: github.event_name != 'pull_request'
Currently it should publish on `main`, `docs` and tags. Before merging I'll drop `docs`.
```yaml
name: Website
on:
  push:
    branches: 
      - main
      - docs
    tags: ["*"]
```

2021-05-17 14:23 UTC, kubukoz commented on .github/workflows/mdoc.yml
> +    if: github.event_name != 'pull_request'
you mean before merging the next PR :D