Documentation and readme cleanup, mima config
ocadotechnology/sttp-oauth2 pull request #86
Opened 2021-05-20 20:05 UTC by majk-p

- introduce contribution guide to docs,
- describe documentation architecture in contribution guide,
- add sbt dynver for latest stable release in docs,
- introduce mima config based on dynver

2021-05-20 21:17 UTC, kubukoz commented on docs/contributing.md
> +## Wroking with documentation
```suggestion
## Working with documentation
```

2021-05-20 21:18 UTC, kubukoz requested changes

2021-05-20 21:18 UTC, kubukoz commented on docs/contributing.md
> +The documentation is build using [mdoc](https://github.com/scalameta/mdoc) combined with [docusaurus v2](https://docusaurus.io/).
```suggestion
The documentation is built using [mdoc](https://github.com/scalameta/mdoc) combined with [docusaurus v2](https://docusaurus.io/). 
```

2021-05-20 21:18 UTC, kubukoz commented on docs/contributing.md
> +In the first console run `sbt "docs/mdoc --watch"`.
I would rather recommend people use sbt interactively, as a good practice :)

2021-05-21 06:07 UTC, majk-p commented on docs/contributing.md
> +In the first console run `sbt "docs/mdoc --watch"`.
Sure

2021-05-21 06:17 UTC, tplaskowski approved these changes

2021-05-21 06:46 UTC, pkowalcze requested changes
Looking good, just a few grammatical fixes here and there to be done 👍

2021-05-21 06:46 UTC, pkowalcze commented on README.md
> +To use this library add following dependency to yout `build.sbt`
```suggestion
To use this library add the following dependency to your `build.sbt`
```

2021-05-21 06:46 UTC, pkowalcze commented on build.sbt
> +lazy val docs = project // new documentation project
I think we don't need this comment?

2021-05-21 06:46 UTC, pkowalcze commented on docs/contributing.md
> +This is an early stage project. The codebase is prone to change. All suggestions welcome, please create issue describing your problem before contributing.
```suggestion
This is an early stage project. The codebase is prone to change. All suggestions are welcome, please create an issue describing your problem before contributing.
```

2021-05-21 06:46 UTC, pkowalcze commented on docs/contributing.md
> +If it's your first time, remember to run `npm install` in the `./website` directory
A nitpick, but it might be a good idea to put this info before the start command. Someone might just close the docs right after starting up the docusaurus and then wonder why isn't it working

2021-05-21 06:46 UTC, pkowalcze commented on docs/contributing.md
> +The raw documentation goes through few steps process before the final website is created.
```suggestion
The raw documentation goes through a few steps process before the final website is created.
```

2021-05-21 06:49 UTC, majk-p commented on build.sbt
> +lazy val docs = project // new documentation project
Don't have strong opinion, I guess this is self explanatory so we can drop it

2021-05-21 06:51 UTC, majk-p commented on docs/contributing.md
> +If it's your first time, remember to run `npm install` in the `./website` directory
Then they'll either follow the docs or let go. I think this line is useless for most of contributors, so it should remain below.

2021-05-21 06:57 UTC, pkowalcze approved these changes

2021-05-21 07:29 UTC, merged